# Generated by Django 5.0.6 on 2024-07-03 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StreamSniper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('riotIdGameName', models.CharField(max_length=255)),
                ('riotIdTagline', models.CharField(max_length=255)),
            ],
            options={
                'unique_together': {('riotIdGameName', 'riotIdTagline')},
            },
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('win_with_quin', models.PositiveSmallIntegerField(default=0)),
                ('loss_with_quin', models.PositiveSmallIntegerField(default=0)),
                ('win_against_quin', models.PositiveSmallIntegerField(default=0)),
                ('loss_against_quin', models.PositiveSmallIntegerField(default=0)),
                ('total_games', models.PositiveSmallIntegerField(default=0)),
                ('streamsniper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='streamsnipers.streamsniper')),
            ],
            options={
                'unique_together': {('streamsniper',)},
            },
        ),
    ]
